default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: foodiehub_development

test:
  <<: *default
  database: foodiehub_test

production:
  <<: *default
  database: foodiehub_production
  username: foodiehub
  password: <%= ENV['FOODIEHUB_DATABASE_PASSWORD'] %>
